import type { Product } from './types';

export const DEMO_PRODUCTS: Product[] = [
  /* ── Electricals ──────────────────────────────────────────────── */
  {
    id: 'elec-001',
    item_name: 'Havells 8-Module Crabtree Switch Board',
    brand: 'Havells',
    category: 'Electricals',
    description: 'Premium modular switch board with 8-module configuration, dust-proof design, and high-grade polycarbonate body.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'elec-002',
    item_name: 'Philips LED Bulb 9W Cool Day Light',
    brand: 'Philips',
    category: 'Electricals',
    description: 'Energy-efficient 9W LED bulb, 6500K cool daylight, B22 base, 800 lumens, 15,000-hour lifespan.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'elec-003',
    item_name: 'Finolex 1.5mm FR PVC Cable – 90m',
    brand: 'Finolex',
    category: 'Electricals',
    description: 'ISI-certified FR-grade single-core copper wire. Flame-retardant insulation, ideal for household wiring.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'elec-004',
    item_name: 'Schneider Electric iC60 32A MCB',
    brand: 'Schneider',
    category: 'Electricals',
    description: 'Single-pole 32A miniature circuit breaker, C-curve, IEC 60898 compliant, breaking capacity 6kA.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'elec-005',
    item_name: 'Kirloskar Star 1 HP Self-Priming Pump',
    brand: 'Kirloskar',
    category: 'Electricals',
    description: 'Single-phase 1HP self-priming centrifugal pump. Max head 35m, max discharge 2400 LPH.',
    images: [],
    stock_status: 'Out of Stock',
  },
  {
    id: 'elec-006',
    item_name: 'Anchor Roma 6A 3-Pin Socket',
    brand: 'Anchor',
    category: 'Electricals',
    description: 'Modular 6A 3-pin socket with shutter, child-safe design. Compatible with Anchor Roma series.',
    images: [],
    stock_status: 'In Stock',
  },

  /* ── Plumbing ─────────────────────────────────────────────────── */
  {
    id: 'plmb-001',
    item_name: 'Astral CPVC Pipe 1" – 3 Metre',
    brand: 'Astral',
    category: 'Plumbing',
    description: 'CPVC hot & cold water pipe, ISI marked. Operating temperature up to 93°C. 3 m per piece.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'plmb-002',
    item_name: 'Jaguar Single Lever Basin Mixer',
    brand: 'Jaguar',
    category: 'Plumbing',
    description: 'Chrome-finished single-lever basin mixer tap with aerator. 1/4-turn ceramic disc cartridge.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'plmb-003',
    item_name: 'Essex PVC Ball Valve 1"',
    brand: 'Essex',
    category: 'Plumbing',
    description: 'Heavy-duty PVC ball valve with stainless steel ball and PTFE seat. Pressure rating 10 bar.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'plmb-004',
    item_name: 'Supreme UPVC Column Pipe 63mm – 6m',
    brand: 'Supreme',
    category: 'Plumbing',
    description: 'UPVC column pipe for submersible pumps, ISI marked. 63mm OD, 6-metre length.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'plmb-005',
    item_name: 'Parryware Agate Wall-Hung WC',
    brand: 'Parryware',
    category: 'Plumbing',
    description: 'Wall-hung ceramic WC with soft-close seat cover. WELS 3-star water rating, dual flush 3/6L.',
    images: [],
    stock_status: 'Out of Stock',
  },
  {
    id: 'plmb-006',
    item_name: 'Vectus 500L Overhead Water Tank',
    brand: 'Vectus',
    category: 'Plumbing',
    description: '500-litre 4-layer UV-stabilised polyethylene tank with inlet, outlet and overflow connections.',
    images: [],
    stock_status: 'In Stock',
  },

  /* ── Paints (Berger) ──────────────────────────────────────────── */
  {
    id: 'pnt-001',
    item_name: 'Berger WeatherCoat Premium Exterior – 10L',
    brand: 'Berger',
    category: 'Paints',
    description: '100% acrylic exterior emulsion with superior water resistance, anti-algae & anti-fungal protection.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'pnt-002',
    item_name: 'Berger Silk Luxury Interior Emulsion – 4L',
    brand: 'Berger',
    category: 'Paints',
    description: 'Premium sheen finish interior emulsion. Washable, low-VOC, 1500+ colour shades available.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'pnt-003',
    item_name: 'Berger Easy Clean Matt Interior – 4L',
    brand: 'Berger',
    category: 'Paints',
    description: 'Stain-resistant matt interior paint. Wipe-clean surface, anti-bacterial, low odour formulation.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'pnt-004',
    item_name: 'Berger Rangoli Total Care Exterior – 4L',
    brand: 'Berger',
    category: 'Paints',
    description: 'Economy exterior emulsion with rainshield protection. Ideal for cement, masonry and asbestos surfaces.',
    images: [],
    stock_status: 'In Stock',
  },
  {
    id: 'pnt-005',
    item_name: 'Berger Bison Acrylic Distemper – 5 kg',
    brand: 'Berger',
    category: 'Paints',
    description: 'Ready-to-use interior distemper. Smooth finish, easy application, wide colour range.',
    images: [],
    stock_status: 'Out of Stock',
  },
  {
    id: 'pnt-006',
    item_name: 'Berger WallFlex Interior Primer – 20L',
    brand: 'Berger',
    category: 'Paints',
    description: 'Alkali-resistant interior primer for new plaster. Improves paint adhesion and coverage.',
    images: [],
    stock_status: 'In Stock',
  },
];
